[package]
name = "rust-for-liberty"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = {version = "0.12.12", features = ["json"]}
futures = "0.3"
tokio = {version = "1.12.0", features = ["full"]}